### ISSUE TITLE
Not properly handling future print statements

### ISSUE THREAD

**Issue by LivInTheLookingGlass** [zestyping/star-destroyer#2]
I'm running this on https://github.com/gappleto97/p2p-project/tree/beta/py

Running from python 2 yields an SyntaxError, despite this being handled correctly by my code. Because `__future__` statements must be on the first line, this seems like an easy candidate to check.

Loved your lightning talk by the way.

**Comment by zestyping** [comment]
Thanks!

I tried cloning your repo and running star_destroyer works fine for me.  I ran it like this:

```
python2.7 -m star_destroyer -e py
```

Is it possible you were running with a version of Python before 2.7?

**Comment by sils** [comment]
Does it work with python 3?

**Comment by sils** [comment]
oh wrong thread. Never mind.

**Comment by zestyping** [comment]
Yes, it works with Python 3 (as well as Python 2.7).

**Comment by zestyping** [comment]
I'm closing this because I suspect this problem only occurs in Python 2.6.  Feel free to reopen if I have misunderstood the problem, thanks!
